spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/appdb
    username: appuser
    password: apppass

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
